### ISSUE TITLE
I tried it and it didn't tell me what to do next so I don't have to think about it.

### ISSUE THREAD

**Issue by kebno** [wicker/wickertracker#1]
This makes me question open-source software everywhere.....

**Comment by kebno** [comment]
It just said "Hello world!"  What does that mean? Am I supposed to say that?  
Maybe I don't have the right version of Python installed.

**Comment by wicker** [comment]
It's basically just a flask app.

**Comment by kebno** [comment]
OK.  Don't worry.  I just did this and got it to work: `pip install just-make-it-work-i-don't-want-to-code-anymore-please`

But if you didn't want to use that package, I could collaborate with you.  I've made flask apps that are about 10-20 times longer than yours.  I guess that makes me a pro?

**Comment by kebno** [comment]
Or did I just not understand the README?  Is this one of those GPS-tracker-solutions so people won't escape house arrest?

**Comment by wicker** [comment]
What I did instead was to install Zim (the desktop wiki solution!!!11!) on
every computer I have access to and then make a new private repo with all
my zim stuff in it. Wham, bam, done.

**Comment by kebno** [comment]
:sparkles:   :sparkles:   :sparkles: :clap: :cake:
